---
# SpringAdmin
spring:
  boot:
    admin:
      url: http://localhost:8090
      username: admin
      password: admin


---
## Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://cn.pree1:8111/eureka/,http://cn.pree2:8112/eureka/,http://cn.pree3:8113/eureka/
  instance:
    hostname: localhost
    prefer-ip-address: false
    statusPageUrl: http://${eureka.instance.hostname}:${server.port}/info
    healthCheckUrl: http://${eureka.instance.hostname}:${server.port}/health
    leaseRenewalIntervalInSeconds: 10
    homePageUrl: https://${eureka.instance.hostname}:${server.port}/
    metadataMap: 
       instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}



